---
run:
  timeout: 5m

linters:
  disable-all: true
  enable:
  - bodyclose
  - deadcode
  - dogsled
  - errcheck
  - gochecknoglobals
  - goconst
  - gocritic
  - goimports
  - golint
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - ineffassign
  - interfacer
  - maligned
  - misspell
  - nakedret
  - staticcheck
  - structcheck
  - stylecheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - varcheck
  - nolintlint
  - scopelint
  - whitespace
  - gocognit
  - gocyclo
  - gomnd
  - lll
  - nestif

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/mibk/dupl
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 20
  govet:
    check-shadowing: true
    enable-all: true
